### PR TITLE
feat: support Solarium data collector via dispatching events

### PR DESCRIPTION
**Pull request by gsdevme**
This adds the ability to Dispatch the events the Solarium Bundle is listening to provide the Solr toolbar

### CODE REVIEW

**Review by shieldo — CHANGES_REQUESTED** [review]
The plugin does not, and should not, have a dependency on the Symfony event dispatcher component.

Could you re-do this to include PSR-14 ([psr/event-dispatcher](https://packagist.org/packages/psr/event-dispatcher)), and to use that instead? Given that it's optional, please include it as a dev dependency.

**Comment by gsdevme** [comment]
Given solarium has a dependency directly on Symfony EventDispatcher I'm not sure PSR-14 would really make sense here. Im assuming this plugin only needs to be agnostic as solarium is itself. 

it's a guarantee that Symfony Event Dispatcher will exist and its not interoperable (in solarium)

https://github.com/solariumphp/solarium/blob/4.x/composer.json#L16
https://github.com/solariumphp/solarium/blob/master/composer.json#L19

**Comment by shieldo** [comment]
You're totally right, sorry! OK, this is fine then - just add the event dispatcher component as a dev dependency for this package and the change is good to go 👍

**Comment by gsdevme** [comment]
Thats it updated now 👍

**Pull request merged**
